# Usa una imagen oficial de Node.js como base
FROM node:18-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y package-lock.json antes de instalar dependencias
# para aprovechar la caché de Docker y acelerar las construcciones
COPY package*.json ./

# Instala solo las dependencias de producción
RUN npm install --only=production

# Copia el resto de la aplicación
COPY . .

# Expone el puerto en el que corre la aplicación (ajusta según sea necesario)
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
